### ISSUE TITLE
Replace Poetry with PDM

### ISSUE THREAD

**Issue by Callum027** [buildarr/buildarr#129]
PDM uses standards-compliant project files (PEP-517 and PEP-621), and doesn't use any custom `setuptools` build backends during package installation.

https://pdm-project.org

**Comment by Callum027** [comment]
When updating the release CI pipelines, split building the wheel and publishing to PyPI into two separate job, using artifacts to share it between them. This allows for adding a third parallel job that adds the wheel file to the release.

**Comment by Callum027** [comment]
At the same time, switch to automatic version definitions using [`setuptools-scm`](https://setuptools-scm.readthedocs.io/en/latest/).

**Comment by ssbarnea** [comment]
With the risk of being hated for asking... I need to ask why picking two controversial packaging solutions instead of just going for the good old and very well supported setuptools?

I have more a decade of python development and I am so glad I avoided poetry. Funny bit is that this is the second time I face pdm, which is even less popular and guess what... is broken https://github.com/buildarr/buildarr/issues/227 and even trying to run locally it fails. Last CI job run more than 6 months ago and it would have shown the problems.

There is a big chain of broken things directly related to the packaging tool used combined with GHA pipelines that needs some maintenance.

Any chance to get this into a shape that would be easier to contribute to?
